CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_RECOMMENDER_EMAIL VARCHAR2(255)
);

SELECT *
FROM TBL_MEMBER;

DROP TABLE TBL_MEMBER;