--/*
--   요구사항
--   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
--   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
--   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
--*/
--
---- 음료수
---- TBL_SOFT_DRINK
---- 이름, 가격, 재고, 재조일
--CREATE SEQUENCE SEQ_SOFT_DRINK;
--CREATE TABLE TBL_SOFT_DRINK(
--   ID NUMBER CONSTRAINT PK_SOFT_DRINK PRIMARY KEY,
--   SOFT_DRINK_NAME VARCHAR2(255) NOT NULL,
--   SOFT_DRINK_PRICE NUMBER DEFAULT 0,
--   SOFT_DRINK_STOCK NUMBER DEFAULT 999,
--   SOFT_DRINK_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
---- 상품
---- TBL_PRODUCT
---- 이름, 재고
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--   PRODUCT_NAME VARCHAR2(255) NOT NULL,
--   PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
---- 사용자
---- TBL_USER
---- 이름, 주소, 번호
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,   
--   USER_NAME VARCHAR2(255) NOT NULL,
--   USER_ADDRESS VARCHAR2(255) NOT NULL,
--   USER_PHONE VARCHAR2(255) NOT NULL
--);
--
---- 주문
---- TBL_ORDER
---- 주문날짜, USER_ID, SOFT_DRINK_ID
--CREATE SEQUENCE SEQ_ORDER;
--CREATE TABLE TBL_ORDER(
--   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
--   ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   USER_ID NUMBER,
--   SOFT_DRINK_ID NUMBER,
--   CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
--   REFERENCES TBL_USER(ID),
--   CONSTRAINT FK_ORDER_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
--   REFERENCES TBL_SOFT_DRINK(ID)
--);
--
---- 당첨(운)
---- TBL_LOTTERY
---- SOFT_DRINK_ID
--CREATE SEQUENCE SEQ_LOTTERY;
--CREATE TABLE TBL_LOTTERY(
--   ID NUMBER CONSTRAINT PK_LOTTERY PRIMARY KEY,
--   SOFT_DRINK_ID NUMBER,
--   CONSTRAINT FK_LOTTERY_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
--   REFERENCES TBL_SOFT_DRINK(ID)
--);
--
---- 추첨
---- TBL_CIRULATION
---- LOTTERY_ID, PRODUCT_ID
--CREATE SEQUENCE SEQ_CIRULATION;
--CREATE TABLE TBL_CIRULATION(
--   ID NUMBER CONSTRAINT PK_CIRULATION PRIMARY KEY,
--   LOTTERY_ID NUMBER,
--   PRODUCT_ID NUMBER,
--   CONSTRAINT FK_CIRULATION_LOTTERY FOREIGN KEY(LOTTERY_ID)
--   REFERENCES TBL_LOTTERY(ID),
--   CONSTRAINT FK_CIRULATION_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID)
--);
--
--
---- 배송
---- TBL_DELIVERY
---- PRODUCT_ID, USER_ID
--CREATE SEQUENCE SEQ_DELIVERY;
--CREATE TABLE TBL_DELIVERY(
--   ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
--   PRODUCT_ID NUMBER,
--   USER_ID NUMBER,
--   CONSTRAINT FK_DELIVERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID),
--   CONSTRAINT FK_DELIVERY_USER FOREIGN KEY(USER_ID)
--   REFERENCES TBL_USER(ID)
--);


/*
   요구사항
   이커머스 창업 준비중입니다. 기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
   기업의 정보는 기업 이름, 주소, 대표번호가 있고
   사용자 정보는 이름, 주소, 전화번호가 있습니다. 결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며,
   상품의 정보도 필요합니다. 상품의 정보는 이름, 가격, 재고입니다.
   사용자는 등록한 카드의 정보를 저장할 수 있으며, 카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
*/
--
---- 회사(TBL_COMPANY)
---- 이름, 주소, 대표번호
--CREATE SEQUENCE SEQ_COMPANY;
--CREATE TABLE TBL_COMPANY(
--   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
--   COMPANY_NAME VARCHAR2(255) NOT NULL,
--   COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
--   COMPANY_PHONE VARCHAR2(255)
--);
--
---- 사용자(TBL_MEMBER)
---- 이름, 주소, 전화번호
--CREATE SEQUENCE SEQ_MEMBER;
--CREATE TABLE TBL_MEMBER(
--   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
--   MEMBER_NAME VARCHAR2(255) NOT NULL,
--   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
--   MEMBER_PHONE VARCHAR2(255) NOT NULL
--);
--
---- 상품(TBL_PRODUCT)
---- 이름, 가격, 재고
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--   PRODUCT_NAME VARCHAR2(255) NOT NULL,
--   PRODUCT_PRICE NUMBER DEFAULT 0,
--   PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
---- 주문(TBL_ORDER)
---- MEMBER_ID, PRODUCT_ID
--CREATE SEQUENCE SEQ_ORDER;
--CREATE TABLE TBL_ORDER(
--   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
--   MEMBER_ID,
--   PRODUCT_ID,
--   CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
--   REFERENCES TBL_MEMBER(ID),
--   CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID)
--);
--
---- 카드(TBL_CARD)
---- 카드이름, 카드은행, 카드날짜, 카드번호, MEMBER_ID
--CREATE SEQUENCE SEQ_CARD;
--CREATE TABLE TBL_CARD(
--   ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
--   CARD_NAME VARCHAR2(255) NOT NULL,
--   CARD_BANK VARCHAR2(255) NOT NULL,
--   CARD_DATE DATE DEFAULT CURRENT_TIMESTAMP,
--   MEMBER_ID NUMBER,
--   CONSTRAINT FK_CARD_MEMBER FOREIGN KEY(MEMBER_ID)
--   REFERENCES TBL_MEMBER(ID)
--);
--
---- 결제(TBL_PAY) 
---- ORDER_ID, CARD_ID, COMPANY_ID
--CREATE SEQUENCE SEQ_PAY;
--CREATE TABLE TBL_PAY(
--   ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
--   ORDER_ID NUMBER,
--   CARD_ID NUMBER,
--   COMPANY_ID NUMBER,
--   CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORDER_ID)
--   REFERENCES TBL_ORDER(ID),
--   CONSTRAINT FK_PAY_CARD FOREIGN KEY(CARD_ID)
--   REFERENCES TBL_CARD(ID),
--   CONSTRAINT FK_PAY_COMPANY FOREIGN KEY(COMPANY_ID)
--   REFERENCES TBL_COMPANY(ID)
--);
--
--
--
---- DML
---- DATE 7Byte
---- CURRENT_TIMESTAMP 11Byte
--CREATE SEQUENCE SEQ_MEMBER;
--CREATE TABLE TBL_MEMBER(
--   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
--   MEMBER_NAME VARCHAR2(255) NOT NULL,
--   MEMBER_AGE NUMBER,
--   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
--   MEMBER_PHONE VARCHAR2(255),
--   MEMBER_GENDER CHAR(6),
--   MEMBER_CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   MEMBER_CREATE_DATE DATE DEFAULT SYSDATE 
--);
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_PHONE, MEMBER_GENDER)
--VALUES (SEQ_MEMBER.NEXTVAL, '홍길동', 20, '서울시 강남구', '010-1234-5678', '남자');
--
--INSERT INTO TBL_MEMBER
--VALUES (SEQ_MEMBER.NEXTVAL, '장보고', 30, '서울시 종로구', '010-4567-7890', '남자', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES (SEQ_MEMBER.NEXTVAL, '이순신', 40, '경기도 성남시', '남자');
--
--
---- 데이터 추가
---- 김영희, 25살, 서울시 영등포구, 여자 
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES (SEQ_MEMBER.NEXTVAL, '김영희', 25, '서울시 영등포구', '여자');
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES (SEQ_MEMBER.NEXTVAL, '김철수', 35, '서울시 종로구', '남자');
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES (SEQ_MEMBER.NEXTVAL, '이규학', 28, '경기도 하남시', '남자');
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES (SEQ_MEMBER.NEXTVAL, '써니', 33, '경기도 남양주시', '남자');
--
--
--UPDATE TBL_MEMBER
--SET MEMBER_GENDER = '여자'
--WHERE ID = 4;
--
--
--UPDATE TBL_MEMBER
--SET MEMBER_GENDER = NULL
--WHERE ID = 3;
--
--
--DELETE FROM TBL_MEMBER
--WHERE ID = 3;
--
--
---- 이름이 홍길동인 사람의 전화번호를 010-4456-7788로 변경
--UPDATE TBL_MEMBER
--SET MEMBER_PHONE = '010-4456-7788'
--WHERE MEMBER_NAME = '홍길동';
--
---- 서울시 영등포구에 거주중인 사람의 데이터 삭제
--DELETE FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS = '서울시 영등포구';
--
---- 나이가 20대인 사용자들의 정보를 조회
---- 20 ~ 29
--
--SELECT * 
--FROM TBL_MEMBER
--WHERE MEMBER_AGE >= 20 AND MEMBER_AGE <= 29;
--
--
---- 회원 중 남자만 조회
--SELECT *
--FROM TBL_MEMBER
--WHERE MEMBER_GENDER = '남자';
--
---- 회원 중 남자 중 이름만 조회
--SELECT MEMBER_NAME, MEMBER_AGE
--FROM TBL_MEMBER
--WHERE MEMBER_GENDER = '남자';
--
--
--SELECT * FROM TBL_MEMBER;
--
--
--
--/*
-- * 
-- * LIKE: 포함된 문자열 값을 찾고, 문자의 개수도 제한을 줄 수 있다.
-- * 
-- * %: 모든 것
-- * _: 글자 수
-- * 
-- * 예시
-- '%A' : A로 끝나는 모든 값(NDFLSNJFA, 123NFJA, ...)
-- 'A%' : A로 시작하는 모든 값(AA, ANDKFS, AJD, ...)
-- 'A__' : A로 시작하며 3글자인 값(ABC, AAA, ADD, ...)
-- '_A' : A로 끝나며 2글자인 값(FA, CA, DA, ...)
-- '%A%' : A가 포함된 값(APPLE, BANANA, TASK, ...)
-- * 
-- * */
--
----서울에 살고 있는 사용자들 조회
--SELECT *
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS LIKE '서울%';
--
---- 주소가 시로 끝나는 사용자들 조회
--SELECT *
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS LIKE '%시';
--
---- 종로에 살고있는 사용자의 나이 조회
--SELECT MEMBER_AGE
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS LIKE '%종로%';
--
---- 핸드폰 번호가 있는 사용자만 조회
---- IS NULL
---- IS NOT NULL
--SELECT * 
--FROM TBL_MEMBER
--WHERE MEMBER_PHONE IS NULL;
--
---- 경기도에 살고 있지 않은 사용자들의 이름 조회
--SELECT *
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS NOT LIKE '경기도%';
--
--
---- 가상 테이블: DUAL
--SELECT SYSDATE FROM DUAL;
--
---- ORACLE 스크립트 언어
---- 같은 컬럼을 여러 번 조회할 수 있다.
---- ALIAS(별칭): 최종 테이블의 속성 이름을 변경할 수 있다
---- 컬럼명 옆에 ""(더블쿼터)를 사용하여 붙인다.
--
--SELECT MEMBER_NAME "이름", MEMBER_AGE "회원 나이", MEMBER_AGE - 1 "만 나이"
--FROM TBL_MEMBER;
--
---- 만나이는 파생 변수
--
---- 연결 (||)
--SELECT 'ABCD' || 'E' FROM DUAL;
--SELECT CONCAT('A', 'A') FROM DUAL;
--
---- NULL은 무시
--SELECT CONCAT('A', NULL) FROM DUAL; 
--SELECT 'ABCD' || NULL FROM DUAL;
--
--SELECT MEMBER_NAME || '님' "이름"
--FROM TBL_MEMBER;
--
---- 회원 나이에 '살'을 붙여서 출력
---- EX) 20살
--SELECT MEMBER_AGE || '살' "나이"
--FROM TBL_MEMBER;
--
---- 문자열의 길이
--SELECT LENGTH(MEMBER_ADDRESS), MEMBER_ADDRESS
--FROM TBL_MEMBER;
--
---- 문자열을 자르기 SUBSTR()
---- 인덱스 1부터 시작
---- SUBSTR(찾을 글자, 시작 인덱스, 개수)
--SELECT SUBSTR('HELLO WORLD!', 6, 2)
--FROM TBL_MEMBER;
--
---- 사칙연산
--SELECT MEMBER_AGE + 1 FROM TBL_MEMBER;
--SELECT MEMBER_AGE - 1 FROM TBL_MEMBER;
--SELECT MEMBER_AGE * 20 FROM TBL_MEMBER;
--SELECT MEMBER_AGE / 5 FROM TBL_MEMBER;
--
---- 올림 
--SELECT CEIL(MEMBER_AGE / 5) FROM TBL_MEMBER;
--
---- 반올림
--SELECT ROUND(MEMBER_AGE / 5,  1) FROM TBL_MEMBER;
--
---- 내림 (몫)
--SELECT FLOOR(MEMBER_AGE / 5) FROM TBL_MEMBER;
--
---- 나머지 MOD
--SELECT MOD(MEMBER_AGE, 5) FROM TBL_MEMBER;
--
---- 3문제 ↑ NULL
--SELECT 10 * NULL FROM DUAL;
--SELECT 10 - NULL FROM DUAL;
--SELECT 10 / NULL FROM DUAL;
--SELECT 10 + NULL FROM DUAL;
--
--
--/*집계 함수
-- * 
-- * 평균 AVG()
-- * 최대값 MAX()
-- * 최소값 MIN()
-- * 총 합 SUM()
-- * 개수 COUNT()
-- * 
-- * */
--
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--   PRODUCT_NAME VARCHAR2(255) NOT NULL,
--   PRODUCT_PRICE NUMBER DEFAULT 0,
--   PRODUCT_STOCK NUMBER DEFAULT 999,
--   PRODUCT_CREATE_AT DATE
--);
--
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '규학이의 텀블러', 15000, 10, TO_DATE('2026-01-12 11:25', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '소훈이의 마스크', 20000, 60, TO_DATE('2026-02-20 12:50', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '써니의 마음', 100000, 2, TO_DATE('2025-10-07 10:00', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '하영이의 아이폰', 200000, 1, TO_DATE('2026-03-03 03:03', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '유중의 미', 500000, 5, TO_DATE('2026-02-20 16:00', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '코카콜라의 아들 규호의 코카콜라', 200000, 30, TO_DATE('2026-02-02 15:00', 'YYYY-MM-DD HH24:mi'));
--
--SELECT * FROM TBL_PRODUCT;
--
---- 그룹 함수, 집계 함수는 WHERE 절에서 사용이 불가능하다. 연산 가능
--SELECT MAX(PRODUCT_PRICE)
--FROM TBL_PRODUCT;
--
---- 상품이 모두 판매 되었을 때의 가격의 총액
--SELECT SUM(PRODUCT_PRICE * PRODUCT_STOCK) FROM TBL_PRODUCT;
--
---- 상품 들의 평균 가격
--SELECT AVG(PRODUCT_PRICE) FROM TBL_PRODUCT;
--
--
---- 써니의 마음, 유중의 미, 규혁이의 텀블러 가격의 평균
--SELECT TO_CHAR(AVG(PRODUCT_PRICE), '999,999') || '원' "평 균"
--FROM TBL_PRODUCT
--WHERE ID = 7 OR ID = 9 OR ID = 11;
--
---- WHERE ~ IN (값1, 값2, 값3) == OR 
--SELECT TO_CHAR(AVG(PRODUCT_PRICE), '999,999') || '원' "평 균"
--FROM TBL_PRODUCT
--WHERE ID IN (7, 9, 11);
--
---- COUNT 집계 함수는 NULL을 세지 않아 NULL이 아니라 -> 0이 출력된다.
--SELECT COUNT(NULL) FROM TBL_PRODUCT;
--
---- ORDER BY: 정렬
---- ASC: 오름차순
---- DESC: 내림차순
--
---- 낮은 가격 순
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE ASC;
--
---- 높은 가격 순
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC;
--
---- 최신 등록 순 
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY ID DESC;
--
---- 날짜의 연산
---- 일자 별로 계산
--SELECT PRODUCT_CREATE_AT, PRODUCT_CREATE_AT + 1 / 24 / 60
--FROM TBL_PRODUCT;
--
---- 가장 비싼 상품 조회
--
---- 처음부터 1행
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--FETCH FIRST 3 ROWS ONLY;
--
---- 페이지네이션
---- OFFSET
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (1 - 1) * 3 ROWS FETCH NEXT 3 ROWS ONLY;
--
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (2 - 1) * 3 ROWS FETCH NEXT 3 ROWS ONLY;
--
--SELECT * 
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (3 - 1) * 3 ROWS FETCH NEXT 3 ROWS ONLY;
--
--
--SELECT 500000 - 10000 FROM DUAL;

-- WHERE절에서는 집계 함수, 그룹 함수 사용 불가!!!
--SELECT MAX(PRODUCT_PRICE) - 10000 FROM TBL_PRODUCT
--WHERE MAX(PRODUCT_PRICE) = 50000;


/*
 * GROUP BY: ~별
 * 
 * GROUP BY 컬럼명 HAVING 조건식
 * 
 * */

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER DEFAULT 0,
   PRODUCT_STOCK NUMBER DEFAULT 999
);


SELECT * FROM TBL_PRODUCT;

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 4000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 6000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 5000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 60);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 30);

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 4000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 1000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 6000, 80);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 1000, 40);


INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 4000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 1000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 1000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 10);


-- HAVING
-- 상품 개수가 3개 이상인 상품 조회 
SELECT 
   PRODUCT_NAME, 
   PRODUCT_PRICE, 
   COUNT(PRODUCT_NAME), 
   PRODUCT_PRICE * COUNT(PRODUCT_NAME)
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE
HAVING COUNT(PRODUCT_NAME) >= 3;


SELECT 
   PRODUCT_NAME, 
   PRODUCT_PRICE, 
   COUNT(PRODUCT_NAME), 
   PRODUCT_PRICE * COUNT(PRODUCT_NAME)
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE
HAVING PRODUCT_PRICE >= 5000;


-- 상품의 가격대별 기대수익
SELECT 
   '상품: ' || PRODUCT_NAME "상품명", 
   '가격: ' || TO_CHAR(PRODUCT_PRICE, '0,000') || '원' "상품가격",
   '기대수익: ' || TO_CHAR(PRODUCT_PRICE * SUM(PRODUCT_STOCK), '000,000') || '원' "기대수익"
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE;

-- 재고별 총 판매 액수
-- 서브쿼리에서 해결!
--SELECT PRODUCT_STOCK, PRODUCT_PRICE * SUM(PRODUCT_STOCK), COUNT(PRODUCT_STOCK)
--FROM TBL_PRODUCT
--GROUP BY PRODUCT_STOCK;

-- 서브 쿼리(SUB QUERY)
-- FROM절: IN LINE VIEW
-- SELECT절: SCALAR
-- WHERE절: 

-- 재고가 10개면서, 2000원이 초과하는 상품들 조회
SELECT TBP.*
FROM (
	SELECT *
	FROM TBL_PRODUCT
	WHERE PRODUCT_STOCK = 10
) TBP
WHERE TBP.PRODUCT_PRICE > 2000;

-- 재고가 20, 30, 40인 상품들의 ID를 조회
SELECT TBP.ID
FROM (
	SELECT *
	FROM TBL_PRODUCT
	WHERE PRODUCT_STOCK IN (20, 30, 40)
) TBP;

-- 가장 비싼 상품 조회
SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE = (
	SELECT MAX(PRODUCT_PRICE) 
	FROM TBL_PRODUCT
)

-- 판매 상품의 평균 가격보다 비싼 상품들을 조회
SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE >= (
	SELECT AVG(PRODUCT_PRICE) 
	FROM TBL_PRODUCT
);

-- 정상!
SELECT PRODUCT_PRICE, PRODUCT_STOCK * PRODUCT_PRICE
FROM TBL_PRODUCT;

-- 상품별!
SELECT PRODUCT_NAME, PRODUCT_PRICE
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE;

SELECT 
	PRODUCT_NAME
	PRODUCT_PRICE
	SUM(PRODUCT_STOCK) * PRODUCT_PRICE
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE;

-- 서브쿼리
-- 유저, 게시판, 댓글
-- TBL_USER
-- 이메일(EMAIL), 비밀번호(PASSWORD), 주소(ADDRESS), 생일(BIRTH)

-- 게시판(TBL_POST)
-- 제목(TITLE), 내용(CONTENT), 작성일(CREATE_AT)

-- 댓글(TBL_REPLY)
-- 내용(CONTENT)
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(255) NOT NULL,
	
)







































































