CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_NAME VARCHAR2(255) NOT NULL,
   USER_AGE NUMBER,
   USER_GENDER CHAR(6),
   USER_ADDRESS VARCHAR2(255) NOT NULL,
   USER_PHONE VARCHAR2(255)
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER DEFAULT 0,
   PRODUCT_BRAND VARCHAR2(255),
   PRODUCT_STOCK NUMBER DEFAULT 999
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_TBL_ORDER PRIMARY KEY,
   USER_ID NUMBER,
   PRODUCT_ID NUMBER,
   CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);

/*
 * 유저 정보 더미데이터
 * */
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '홍길동', 20, '남', '서울시 강남구', '01044872848');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '이순신', 30, '남', '경기도 구리시', '01044447224');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '장보고', 40, '남', '경기도 남양주시', '0107131552');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '김철수', 20, '남', '서울시 중랑구', '01055748121');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '김영희', 30, '여', '경기도 수원시', '01071851345');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '이아영', 30, '여', '서울시 종로구', '01024587845');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '정유리', 40, '여', '서울시 강남구', '01043154871');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '최성진', 20, '남', '서울시 강남구', '01025172345');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '강민구', 20, '남', '경기도 분당시', '01084233215');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, '조사랑', 30, '여', '서울시 강서구', '01024771553');

/*
 * 상품 더미데이터
 * */
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '라운드 티셔츠', 25300, '무신사', 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '독일순 스니커즈', 63900, '아디다스', 200);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '블레이저 재킷', 150000, '톰브라운', 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '버지니아', 260000, '닥터마틴', 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '슬립 티셔츠', 79000, '플로랄프로렌', 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '반팔 티셔츠', 27000, '예일', 100);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '척 클래식', 90000, '컨버스', 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '코튼 볼캡', 330000, '버버리', 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '옥스포드 셔츠', 32300, '스파오', 50);

-- 주문 더미 데이터
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 2, 1);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 2, 7);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 2, 6);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 4, 3);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 2, 6);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 4, 6);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 4, 5);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 4, 8);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 5, 1);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 5, 2);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 5, 9);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 5, 6);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 5, 5);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 6, 1);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 6, 5);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 6, 8);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 7, 7);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 7, 2);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 7, 5);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 7, 3);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 8, 1);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 8, 4);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 8, 5);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 8, 6);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 8, 8);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 9, 9);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 9, 5);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 9, 2);
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 9, 2);

-- 1) 상품 이름과 총 판매 매출 조회
SELECT TBP.PRODUCT_NAME AS "상품명", SUM(TBP.PRODUCT_PRICE) AS "총 판매 매출"
FROM TBL_PRODUCT TBP
JOIN TBL_ORDER TBO
ON TBP.ID = TBO.PRODUCT_ID
GROUP BY TBP.PRODUCT_NAME;


-- 2) 상품을 구매한 20 ~ 30대 구매자의 수 조회
SELECT COUNT(DISTINCT TBU.ID) AS "20~30대 구매자 수" 
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID
WHERE TBU.USER_AGE >= 20
	AND TBU.USER_AGE <= 39;


-- 3) 뉴발란스를 구매한 20대 구매자의 이름 조회
SELECT TBU.USER_NAME 
FROM TBL_PRODUCT TBP
JOIN TBL_ORDER TBO 
ON TBP.ID = TBO.PRODUCT_ID
JOIN TBL_USER TBU 
ON TBO.USER_ID = TBU.ID
WHERE TBP.PRODUCT_BRAND LIKE '%뉴발란스%'
	AND TBU.USER_AGE >= 20
	AND TBU.USER_AGE <= 29;

-- 4) 여성의 나이대별 평균 지출 금액 조회
SELECT 
    TBU.USER_AGE AS 나이대, 
    AVG(TBP.PRODUCT_PRICE) AS 평균_지출_금액
FROM TBL_USER TBU
JOIN TBL_ORDER TBO
ON TBU.ID = TBO.USER_ID
JOIN TBL_PRODUCT TBP 
ON TBP.ID = TBO.PRODUCT_ID
WHERE TBU.USER_GENDER = '여'
GROUP BY TBU.USER_AGE;

-- 5) 쇼핑몰의 총 판매 액수 조회
SELECT SUM(TBP.PRODUCT_PRICE) AS "총 판매 액수"
FROM TBL_PRODUCT TBP
JOIN TBL_ORDER TBO 
ON TBP.ID = TBO.PRODUCT_ID;

-- 6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
SELECT * FROM TBL_ORDER;
SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_USER;

SELECT 
    TBU.USER_NAME AS "사용자 이름", 
    TBP.PRODUCT_NAME AS "상품명"
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID 
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID;

-- 6번 문제 잘 모르겠음.

-- 7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
SELECT 
	TBU.*,
	TBP.PRODUCT_NAME
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID 
JOIN TBL_PRODUCT TBP 
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBU.USER_ADDRESS LIKE '경기도%'
ORDER BY TBU.USER_NAME DESC;

-- 8) 30대 남성이 가장 많이 구매한 상품의 이름 조회
SELECT TBP.PRODUCT_NAME 
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID
JOIN TBL_PRODUCT TBP 
ON TBP.ID = TBO.PRODUCT_ID
WHERE TBU.USER_GENDER LIKE '남%'
	AND TBU.USER_AGE >= 30
	AND TBU.USER_AGE <= 39
GROUP BY TBP.PRODUCT_NAME
ORDER BY COUNT(TBO.ID) DESC
FETCH FIRST 1 ROWS ONLY;

-- 9) 가장 적게 판매된 상품의 이름
-- 판매 개수가 0개일 가능성도 있음.
SELECT * FROM TBL_USER;
SELECT * FROM TBL_ORDER;
SELECT * FROM TBL_PRODUCT;

SELECT TBP.PRODUCT_NAME
FROM TBL_PRODUCT TBP 
LEFT JOIN TBL_ORDER TBO 
ON TBP.ID = TBO.PRODUCT_ID
GROUP BY TBP.PRODUCT_NAME
ORDER BY COUNT(TBP.ID) ASC
FETCH FIRST 1 ROWS ONLY;

-- 10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
SELECT TBP.PRODUCT_NAME, TBU.*
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID 
JOIN TBL_PRODUCT TBP 
ON TBP.ID = TBO.PRODUCT_ID
WHERE TBU.USER_AGE > (
	SELECT AVG(USER_AGE)
	FROM TBL_USER
);

-- 11) 20대 남성이 구매한 상품 이름과 주문 건수 조회
SELECT TBP.PRODUCT_NAME,
	COUNT(TBO.ID) AS "주문 건수"
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID 
JOIN TBL_PRODUCT TBP 
ON TBP.ID = TBO.PRODUCT_ID
WHERE TBU.USER_AGE >= 20 
	AND TBU.USER_AGE <= 29
	AND TBU.USER_GENDER LIKE '남%'
GROUP BY TBP.PRODUCT_NAME;

-- 12) 가장 인기가 없는 상품 조회
-- 가장 안팔린 상품
SELECT TBP.PRODUCT_NAME
FROM TBL_PRODUCT TBP 
LEFT JOIN TBL_ORDER TBO 
ON TBP.ID = TBO.PRODUCT_ID
GROUP BY TBP.PRODUCT_NAME
ORDER BY COUNT(TBP.ID) ASC
FETCH FIRST 1 ROWS ONLY;

-- 13) 유저 중 이아영을 김아영으로 이름 변경
UPDATE TBL_USER 
SET USER_NAME = '김아영'
WHERE USER_NAME = '이아영';

-- 14) 신상품 '나이키', '에어맥스 95', 가격 179000원, 재고 200개를 TBL_PRODUCT 테이블에 추가
INSERT INTO TBL_PRODUCT 
VALUES(SEQ_PRODUCT.NEXTVAL, '에어맥스 95', 179000, '나이키', 200);

-- 15) BUYER_NAME이 '김철수'인 사람의 핸드폰 번호를 '010-0000-0000'으로 변경

UPDATE TBL_USER 
SET USER_PHONE = '010-0000-0000'
WHERE USER_NAME = '김철수';

-- 16) PRODUCT_NAME이 '척 클래식'인 상품의 가격을 310000으로 인상
UPDATE TBL_PRODUCT 
SET PRODUCT_PRICE = '310000'
WHERE PRODUCT_NAME = '척 클래식';

-- 17) BUYER_NAME이 '이순신'인 구매자의 정보를 TBL_BUYER에서 삭제 (단, 주문 이력이 있을 경우 삭제되지 않음)

DELETE FROM TBL_USER
WHERE USER_NAME = '이순신'
	AND ID NOT IN (
		SELECT USER_ID
		FROM TBL_ORDER
	);

-- 18) PRODUCT_NAME이 '반팔 티셔츠'인 상품을 TBL_PRODUCT 테이블에서 삭제
SELECT * FROM TBL_USER;
SELECT * FROM TBL_ORDER;
SELECT * FROM TBL_PRODUCT;

DELETE FROM TBL_ORDER
WHERE PRODUCT_ID = 6;

DELETE FROM TBL_PRODUCT
WHERE PRODUCT_NAME = '반팔 티셔츠';

-- 19) '김아영'이 주문한 상품의 이름과 가격을 조회
SELECT 
	TBP.PRODUCT_NAME AS "상품 이름",
	TBP.PRODUCT_PRICE AS "상품 가격"
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID 
JOIN TBL_PRODUCT TBP 
ON TBP.ID = TBO.PRODUCT_ID
WHERE TBU.USER_NAME = '김아영';

-- 20) 각 구매자별로 주문한 상품의 총 개수를 조회 (구매자 이름, 주문 건수)
SELECT 
	TBU.USER_NAME AS "구매자 이름",
	COUNT(TBO.ID) AS "주문 건수"
FROM TBL_USER TBU
JOIN TBL_ORDER TBO 
ON TBU.ID = TBO.USER_ID 
GROUP BY TBU.USER_NAME;

-- 21) 가장 많이 주문된 상품 3개의 이름과 주문 횟수를 내림차순으로 조회

-- 22) 여성 구매자들이 주문한 상품들의 평균 가격을 조회

-- 23) 나이가 30세 이상인 남성 구매자들의 이름과 주소를 조회

-- 24) 재고가 100개 이하인 상품 목록을 브랜드명과 함께 조회

-- 25) '서울시 강북구'에 사는 구매자들의 이름과 핸드폰 번호를 조회

-- 26) 주문 상태가 '배송중'인 주문 내역과 해당 주문자의 이름, 상품명을 조회

-- 27) '최성진' 구매자가 주문한 상품들의 총 가격 합계 조회

-- 28) 상품별 기대 매출 조회

-- 29) '조사랑' 구매자의 주문 내역 중 가장 최근 주문한 상품의 이름과 주문일자를 조회

-- 30) 구매자별로 주문 완료 일자가 가장 빠른 주문 내역을 조회

-- 31) '닥터마틴' 브랜드의 모든 상품 주문 건수를 조회

-- 32) '강민구' 구매자가 주문한 상품들 중 가격이 5만원 이상인 상품의 이름과 가격을 조회

-- 33) '홍길동' 구매자의 주소를 '서울시 송파구'로 수정
-- 34) 구매를 한 번도 한적이 없는 사용자 조회
-- 35) 25세 이하인 구매자의 이름, 나이, 구매한 상품명 조회
-- 36) 코튼 볼캡 상품의 재고 수량을 0으로 변경
-- 37) '무신사' 브랜드 상품을 주문한 구매자들의 이름과 연락처를 조회
-- 38) '김영희' 구매자가 주문한 상품들의 가격 총합을 계산
-- 39) 상품 할인 중 모든 30% 할인가격 조회
-- 40) 구매자별로 주문한 상품 개수를 조회
-- 41) '홍길동' 구매자가 주문한 상품 중 가격이 가장 비싼 상품을 조회
-- 42) '정유리'와 '강민구'가 주문한 상품들을 조회하되 중복 없이 출력
-- 43) '강북구'에 사는 여성 구매자들의 주문 내역을 조회
-- 44) 구매자 이름과 그가 주문한 상품 이름, 주문 상태를 함께 출력
-- 45) 모든 상품의 평균 가격을 구하고, 평균 이상 가격인 상품들을 조회
-- 46) '스파오' 브랜드 상품의 재고를 50개 이하인 경우 재고를 100개로 수정
-- 47) 주문이 한 번도 들어온 적이 없는 상품의 가격 조회
-- 48) 경기도 거주자의 평균 지출액수
-- 49) 구매를 가장 많이 한 사용자