-- 유저(TBL_BUY_USER)
-- 이름(BUY_USER_NAME), 나이(BUY_USER_AGE), 성별(BUY_USER_GENDER), 주소(BUY_USER_ADDRESS), 휴대폰(BUY_USER_PHONE)
CREATE SEQUENCE SEQ_BUY_USER;
CREATE TABLE TBL_BUY_USER(
   ID NUMBER CONSTRAINT PK_BUY_USER PRIMARY KEY,
   BUY_USER_NAME VARCHAR2(255) NOT NULL,
   BUY_USER_AGE NUMBER,
   BUY_USER_GENDER CHAR(6),
   BUY_USER_ADDRESS VARCHAR2(255) NOT NULL,
   BUY_USER_PHONE VARCHAR2(255)
);

-- 상품(TBL_SELL_PRODUCT)
-- 상품명(SELL_PRODUCT_NAME), 가격(SELL_PRODUCT_PRICE), 브랜드(SELL_PRODUCT_BRAND), 재고(SELL_PRODUCT_STOCK)
CREATE SEQUENCE SEQ_SELL_PRODUCT;
CREATE TABLE TBL_SELL_PRODUCT(
   ID NUMBER CONSTRAINT PK_SELL_PRODUCT PRIMARY KEY,
   SELL_PRODUCT_NAME VARCHAR2(255) NOT NULL,
   SELL_PRODUCT_PRICE NUMBER DEFAULT 0,
   SELL_PRODUCT_BRAND VARCHAR2(255),
   SELL_PRODUCT_STOCK NUMBER DEFAULT 999
);

-- 구매(TBL_PRODUCT_ORDER)
-- 요청사항(PRODUCT_ORDER_CONTENT), 구매일시(PRODUCT_ORDER_CREATE_AT)
CREATE SEQUENCE SEQ_PRODUCT_ORDER;
CREATE TABLE TBL_PRODUCT_ORDER(
   ID NUMBER CONSTRAINT PK_TBL_PRODUCT_ORDER PRIMARY KEY,
   BUY_USER_ID NUMBER,
   SELL_PRODUCT_ID NUMBER,
   CONSTRAINT FK_PRODUCT_ORDER_BUY_USER FOREIGN KEY(BUY_USER_ID)
   REFERENCES TBL_BUY_USER(ID),
   CONSTRAINT FK_PRODUCT_ORDER_SELL_PRODUCT FOREIGN KEY(SELL_PRODUCT_ID)
   REFERENCES TBL_SELL_PRODUCT(ID)
);

/*
 * 유저 정보 더미데이터
 * */
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '홍길동', 20, '남', '서울시 강남구', '01044872848');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '이순신', 30, '남', '경기도 구리시', '01044447224');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '장보고', 40, '남', '경기도 남양주시', '0107131552');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '김철수', 20, '남', '서울시 중랑구', '01055748121');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '김영희', 30, '여', '경기도 수원시', '01071851345');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '이아영', 30, '여', '서울시 종로구', '01024587845');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '정유리', 40, '여', '서울시 강남구', '01043154871');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '최성진', 20, '남', '서울시 강남구', '01025172345');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '강민구', 20, '남', '경기도 분당시', '01084233215');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '조사랑', 30, '여', '서울시 강서구', '01024771553');

/*
 * 상품 더미데이터
 * */
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '라운드 티셔츠', 25300, '무신사', 50);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '독일순 스니커즈', 63900, '아디다스', 200);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '블레이저 재킷', 150000, '톰브라운', 20);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '버지니아', 260000, '닥터마틴', 30);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '슬립 티셔츠', 79000, '플로랄프로렌', 10);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '반팔 티셔츠', 27000, '예일', 100);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '척 클래식', 90000, '컨버스', 50);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '코튼 볼캡', 330000, '버버리', 40);
INSERT INTO TBL_SELL_PRODUCT
VALUES(SEQ_SELL_PRODUCT.NEXTVAL, '옥스포드 셔츠', 32300, '스파오', 50);


INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 2, 1);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 2, 7);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 2, 6);

--INSERT INTO TBL_PRODUCT_ORDER
--VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 3, 3);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 2, 6);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 4, 6);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 4, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 4, 8);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 5, 1);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 5, 2);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 5, 9);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 5, 6);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 5, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 6, 1);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 6, 5);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 6, 8);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 7, 7);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 7, 2);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 7, 5);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 7, 3);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 8, 1);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 8, 4);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 8, 5);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 8, 6);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 8, 8);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 9, 9);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 9, 5);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 9, 3);

INSERT INTO TBL_PRODUCT_ORDER
VALUES(SEQ_PRODUCT_ORDER.NEXTVAL, 9, 2);


SELECT * FROM TBL_BUY_USER;
SELECT * FROM TBL_SELL_PRODUCT;
SELECT * FROM TBL_PRODUCT_ORDER;

-- 1. 유저 중 나이가 30살이고 성별이 남자인 사람의 이름 조회
SELECT *
FROM TBL_BUY_USER
WHERE BUY_USER_AGE = 30 AND BUY_USER_GENDER = '남';

-- 2. 성별이 여자이면서 경기도에 살고 있는 사용자가 구매한 상품 목록 조회
SELECT TBP.*, TBU.ID
FROM TBL_BUY_USER TBU
JOIN TBL_PRODUCT_ORDER TBO
ON TBU.ID = TBO.BUY_USER_ID 
JOIN TBL_SELL_PRODUCT TBP
ON TBO.SELL_PRODUCT_ID = TBP.ID
WHERE BUY_USER_GENDER = '여' AND BUY_USER_ADDRESS LIKE '%경기도%';

-- 3. 브랜드 '무신사'를 선호하는 나이대 조회(만약에 동일하면 동일한 것을 모두 출력)
SELECT TBU.BUY_USER_AGE || '대' AS "무신사를 선호하는 나이대"
FROM TBL_PRODUCT_ORDER TBO
JOIN TBL_BUY_USER TBU
ON TBO.BUY_USER_ID = TBU.ID
WHERE SELL_PRODUCT_ID IN (
   SELECT ID
   FROM TBL_SELL_PRODUCT
   WHERE SELL_PRODUCT_BRAND = '무신사'
)
GROUP BY TBU.BUY_USER_AGE
ORDER BY COUNT(TBU.BUY_USER_AGE) DESC
FETCH FIRST 1 ROWS ONLY;

-- 4. 아디다스의 총 매출 조회
SELECT SUM(SELL_PRODUCT_PRICE) "아디다스의 총 매출"
FROM TBL_SELL_PRODUCT TBP
JOIN TBL_PRODUCT_ORDER TBO
ON TBP.ID = TBO.SELL_PRODUCT_ID 
WHERE SELL_PRODUCT_BRAND = '아디다스';

-- 5. 평균 재고보다 작은 상품 조회 
SELECT *
FROM TBL_SELL_PRODUCT 
WHERE SELL_PRODUCT_STOCK < (
   SELECT ROUND(AVG(SELL_PRODUCT_STOCK)) "PRODUCT_AVERAGE"
   FROM TBL_SELL_PRODUCT
);

-- 6. 가장 많이 팔린 상품을 구매한 사용자들 조회

-- 가장 많이 팔린 상품을 구매한 사용자
SELECT TBU.*
FROM TBL_BUY_USER TBU
JOIN (
   SELECT BUY_USER_ID 
   FROM TBL_PRODUCT_ORDER TBO
   WHERE ID = (
      SELECT SELL_PRODUCT_ID
      FROM TBL_PRODUCT_ORDER TBO
      GROUP BY SELL_PRODUCT_ID
      ORDER BY COUNT(SELL_PRODUCT_ID) DESC
      FETCH FIRST 1 ROWS ONLY
   )
) TBO
ON TBO.BUY_USER_ID = TBU.ID; 


SELECT *
FROM TBL_BUY_USER TBU
JOIN (
   SELECT BUY_USER_ID
   FROM (
      SELECT * 
      FROM TBL_PRODUCT_ORDER
      ORDER BY ID ASC
   )
   WHERE ROWNUM = 1
) TBO
ON TBU.ID = TBO.BUY_USER_ID;


-- 컨버스 또는 예일 또는 버버리를 구매한 여성 이름 조회
SELECT TBU.BUY_USER_NAME 
FROM TBL_PRODUCT_ORDER TBO
JOIN TBL_BUY_USER TBU
ON TBO.BUY_USER_ID = TBU.ID
JOIN TBL_SELL_PRODUCT TBP
ON TBO.SELL_PRODUCT_ID = TBP.ID
WHERE TBP.SELL_PRODUCT_BRAND IN ('컨버스', '예일', '버버리') 
   AND TBU.BUY_USER_GENDER = '여';

-- 20대가 가장 많이 구매한 상품
SELECT 
   TBP.SELL_PRODUCT_NAME "20대가 사랑하는 상품", 
   COUNT(TBP.SELL_PRODUCT_NAME) "구매 개수"
FROM TBL_PRODUCT_ORDER TBO
JOIN TBL_BUY_USER TBU
ON TBO.BUY_USER_ID = TBU.ID
JOIN TBL_SELL_PRODUCT TBP
ON TBO.SELL_PRODUCT_ID = TBP.ID
WHERE TBU.BUY_USER_AGE >= 20
   AND TBU.BUY_USER_AGE <= 29
GROUP BY TBP.SELL_PRODUCT_NAME
ORDER BY COUNT(TBP.SELL_PRODUCT_NAME) DESC
FETCH FIRST 1 ROWS ONLY;

-- 최고 매출을 낸 상품 TOP5 조회
SELECT 
   TBP.SELL_PRODUCT_NAME "최고 매출 TOP5", 
   SUM(TBP.SELL_PRODUCT_PRICE) "매출액"
FROM TBL_PRODUCT_ORDER TBO
JOIN TBL_SELL_PRODUCT TBP
ON TBO.SELL_PRODUCT_ID = TBP.ID
GROUP BY TBP.SELL_PRODUCT_NAME, TBP.SELL_PRODUCT_PRICE
ORDER BY SUM(TBP.SELL_PRODUCT_PRICE) DESC
FETCH FIRST 5 ROWS ONLY;


-- 가장 판매 실적이 저조한 상품 조회(판매실적 = 주문수량)
SELECT 
   TBP.SELL_PRODUCT_NAME "판매가 저조한 상품들", 
   COUNT(TBO.SELL_PRODUCT_ID) "개수"
FROM TBL_PRODUCT_ORDER TBO
RIGHT JOIN TBL_SELL_PRODUCT TBP
ON TBO.SELL_PRODUCT_ID = TBP.ID
GROUP BY TBP.SELL_PRODUCT_NAME, TBO.SELL_PRODUCT_ID
HAVING COUNT(TBO.SELL_PRODUCT_ID) = (
   SELECT MIN(SELL_COUNT)
   FROM (
      SELECT COUNT(TBO.SELL_PRODUCT_ID) "SELL_COUNT"
      FROM TBL_PRODUCT_ORDER TBO
      RIGHT JOIN TBL_SELL_PRODUCT TBP
      ON TBO.SELL_PRODUCT_ID = TBP.ID
      GROUP BY TBP.SELL_PRODUCT_NAME, TBO.SELL_PRODUCT_ID
   )
);

-- 서울에 거주자의 1인당 평균 소비 지출액 조회
SELECT AVG(TOTAL_PRICE) "서울에 거주자의 1인당 평균 소비 지출액 조회"
FROM (
   SELECT TBU.BUY_USER_NAME, SUM(TBP.SELL_PRODUCT_PRICE) "TOTAL_PRICE"
   FROM TBL_PRODUCT_ORDER TBO
   JOIN TBL_BUY_USER TBU
   ON TBO.BUY_USER_ID = TBU.ID AND TBU.BUY_USER_ADDRESS LIKE '%서울%'
   JOIN TBL_SELL_PRODUCT TBP
   ON TBO.SELL_PRODUCT_ID = TBP.ID
   GROUP BY TBU.BUY_USER_NAME
);
