-- 서브쿼리
-- 게시판, 댓글
-- 유저(TBL_USER)
-- 이메일(EMAIL), 비밀번호(PASSWORD), 주소(ADDRESS), 생일(BIRTH)
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
   USER_PASSWORD VARCHAR2(255),
   USER_ADDRESS VARCHAR2(255),
   USER_BIRTH DATE
);

-- 게시판(TBL_POST)
-- 제목(TITLE), 내용(CONTENT), 작성일(CREATE_AT)
CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
   ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
   POST_TITLE VARCHAR2(255) NOT NULL,
   POST_CONTENT VARCHAR2(255) NOT NULL,
   POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   USER_ID NUMBER,
   CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

-- 댓글(TBL_REPLY)
-- 내용(CONTENT)
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(255) NOT NULL,
   USER_ID NUMBER,
   POST_ID NUMBER,
   CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
   REFERENCES TBL_POST(ID)
);

-- 유저
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'hong1234@gmail.com', '1234', '경기도 구리시', '1995-03-03');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'jang1234@gmail.com', '1234', '서울시 강남구', '2000-11-14');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'lee1234@gmail.com', '4567', '서울시 종로구', '2003-01-17');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'kcs1234@gmail.com', '1234', '서울시 떡잎마을', '1995-07-07');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'kyh1234@gmail.com', '1234', '서울시 떡잎마을', '1995-08-08');

-- 게시글
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '기분 좋은 금요일! 뀨트북!', '뀨트북 LG 그램! 최고!', 1);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '대훈이가 약해지만 약소훈!', '소들이 많으면? 소스!', 2);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '유중의 미! 웃음벨!', '포도가 자기 소개하면? 포도당!', 3);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '히피의 주인! 뀨잉!', '소가 부족하면? 산소 부족!', 4);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '쟁반으로 사랑을 탐하는 써니!', '만난지 5개월~!', 2);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '카피바라! 카피 보지마라!', '카피바라!', 2);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '미꾸라지! 미꾸미디엄!', '미꾸스몰!', 5);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '미국에 비가 오면!', 'USB', 2);

-- 댓글
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '하하하 너무 재밌어요!', 1, 6);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '히피가 너무 멋져요!', 2, 5);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '코카콜라 너무 맛있어요!!', 2, 4);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '번역을 너무 잘해요!!', 3, 3);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '유중이 너무 멋있어요!!', 3, 5);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '대훈이 몸짱이에요!!', 3, 7);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '철민이 똑똑해요~!', 4, 3);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '떡잎마을이 어디에요?', 4, 6);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '짱구는 몇살이에요?', 4, 6);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '유리는 멀쩡한가요?', 5, 1);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '수지는 첫사랑!', 5, 2);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '서빙은 사랑을 타고~', 5, 3);

-- 서브쿼리
SELECT * FROM TBL_USER;
SELECT * FROM TBL_POST;
SELECT * FROM TBL_REPLY;


-- 서브쿼리
-- 떡잎마을에 살고 있는 사용자가 작성한 게시글 조회
SELECT *
FROM TBL_POST
WHERE USER_ID IN (
   SELECT ID
   FROM TBL_USER
   WHERE USER_ADDRESS LIKE '%떡잎%'
);

-- 카피바라가 들어간 게시글을 작성한 사람의 이름과 주소 조회
SELECT USER_EMAIL "이메일 주소", USER_ADDRESS "주소"
FROM TBL_USER
WHERE ID IN (
   SELECT USER_ID
   FROM TBL_POST
   WHERE POST_TITLE LIKE '%카피바라%' OR POST_CONTENT LIKE '%카피바라%'
);

-- 2번 게시글에 달린 댓글 총 개수
-- 서울시에 살고 있는 사용자가 작성한 게시글에 달린 댓글의 총 개수 
SELECT * FROM TBL_USER;

SELECT COUNT(ID) || '개' "댓글 개수"
FROM TBL_REPLY
WHERE POST_ID = 2;

-- 서울에 살고 있는 사용자들이 작성한 게시글의 달린 댓글들
SELECT COUNT(*) || '개' "서울시에 살고있는 사용자가 작성한 게시들의 달린 댓글 수"
FROM TBL_REPLY
WHERE POST_ID IN (
   SELECT ID
   FROM TBL_POST
   WHERE USER_ID IN (
      SELECT ID
      FROM TBL_USER
      WHERE USER_ADDRESS LIKE '서울%'
   )
);

-- 게시글 내용에 미국이 들어간 사용자의 이메일
SELECT USER_EMAIL "게시글 내용에 미국이 들어간 사용자의 이메일"
FROM TBL_USER
WHERE ID IN (
   SELECT USER_ID
   FROM TBL_POST
   WHERE POST_TITLE LIKE '%미국%' OR POST_CONTENT LIKE '%미국%'
);


-- 평균 댓글 개수보다 많이 달린 게시글
-- 평균 댓글 개수
SELECT *
FROM TBL_POST
WHERE ID IN (
   SELECT POST_ID
   FROM TBL_REPLY
   GROUP BY POST_ID
   HAVING COUNT(POST_ID) >= (
      SELECT ROUND(AVG(POST_COUNT), 1)
      FROM (
         SELECT COUNT(POST_ID) "POST_COUNT"
         FROM TBL_REPLY
         GROUP BY POST_ID
      )
   )
);

-- 가장 댓글이 많이 달린 게시글을 작성한 사용자
SELECT *
FROM TBL_USER
WHERE ID IN (
   SELECT USER_ID
   FROM TBL_POST
   WHERE ID IN (
      SELECT POST_ID
      FROM TBL_REPLY
      GROUP BY POST_ID
      HAVING COUNT(POST_ID) = (
         SELECT MAX(POST_ID)
         FROM (
            SELECT COUNT(POST_ID) "POST_ID"
            FROM TBL_REPLY
            GROUP BY POST_ID
         )
      )
   )
);

-- 가장 많이 달린 댓글의 개수
SELECT MAX(POST_ID)
FROM (
   SELECT COUNT(POST_ID) "POST_ID"
   FROM TBL_REPLY
   GROUP BY POST_ID
);


-- 경기도에 거주하면서 댓글을 단 사용자 조회
SELECT *
FROM TBL_REPLY
WHERE USER_ID IN (
   SELECT ID
   FROM TBL_USER
   WHERE USER_ADDRESS LIKE '%경기도%'
);


-- 댓글에 ?가 들어간 댓글을 작성한 사용자 조회
SELECT *
FROM TBL_USER
WHERE ID IN (
   SELECT USER_ID
   FROM TBL_REPLY
   WHERE REPLY_CONTENT LIKE '%?%'
);

-- CASE문
-- 값을 대체할 때 사용하는 문장
-- SELECT 절에서 사용된다.
SELECT 
   CASE USER_PASSWORD
      WHEN '1234' THEN '일이삼사'
      WHEN '4567' THEN '사오육칠'
      ELSE '다른거'
   END
FROM TBL_USER;


-- 생일이 1990년도에 태어났다면 1990년도로 출력
-- 생일이 2000년도에 태어났다면 2000년도로 출력
SELECT 
   CASE
      WHEN USER_BIRTH >= TO_DATE('2000-01-01', 'YYYY-MM-DD') THEN '2000년생'
      WHEN USER_BIRTH <= TO_DATE('2000-01-01', 'YYYY-MM-DD') THEN '1990년생'
   END
FROM TBL_USER;


SELECT *
FROM TBL_USER;

-- CASE문
-- 경기도에 살고 있는 사용자라면 경기도인
-- 서울시에 살고 있는 사용자라면 서울인으로 출력
SELECT 
   CASE 
      WHEN USER_ADDRESS LIKE '%경기도%' THEN '경기도인'
      WHEN USER_ADDRESS LIKE '%서울%' THEN '서울인'
   END
FROM TBL_USER;






















